server:
  port: 80

spring:
  application:
    name: nacos-order-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

#消费者将要去访问的微服务名称（注册进nacos的微服务提供者，可以不写）
service-url:
  nacos-user-service: http://nacos-payment-service/zn/payment


