server:
  port: 3344

spring:
  application:
    name: cloud-config-center #注册进Eureka服务器的做服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/bandunianhua/springcloud-config.git #GitHub上面的git仓库名字
    ####搜索目录
          search-paths:
           - springcloud-config
          username: 1750812768@qq.com
          password: 7464xiong
      ####读取分支
      label: main


#服务注册到eureka地址
eureka:
  instance:
    hostname: gateway-cloud-service
  client: #服务提供者provider性册住eurake服务列表内
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群版

#rabbitmq相关配置
rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest

##rabbitmq相关配置,暴露bus刷新配置的端点
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: "bus-refresh"