server:
  port: 8081

spring:
  application:
    name: cloud-applyment-service
  zipkin:
    base-url: http://localhost:9411  #需要启动sleuth服务端
    sleuth:
      sampler:
      #采样率值介于0到1之间，1则表示全部采集
      probability: 1

#  cloud:
#    #Config客户端配置
#    config:
#      label: main #分支名称
#      name: config #配置文件名称
#      profile: dev #读取后级名称 上述3个综合：main分支上config-dev.yml的配置文件被读取http://config-3344.com:3344/main/config-dev.yml
#      uri: config-3344.com:3344/ #配置中心地址k

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/testcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 7464xiong

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true
    #是否从Eurekaserver抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡 I
    fetchRegistry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群版
  instance:
    #项目在Eurake的别名
    instance-id: payment-8081
    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒（默认是30秒）
    lease-renewal-interval-in-seconds: 2
    #Eureka服务端在收到最后一次心跳后等待时间上限，单位为秒（默认是90秒），超时将剔除服务
    lease-expiration-duration-in-seconds: 5

##rabbitmq相关配置
#rabbitmq:
#  host: localhost
#  port: 5672
#  username: guest
#  password: guest


mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-handlers-package: com.zn.springcloud.domain

