server:
  port: 9527

spring:
  application:
    name: gateway-cloud
  cloud:
    gateway:
      discovery:
        locator:
          enabled：true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
#        - id: payment_routh             #payment_route  #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          #uri: http://localhost:8081    #匹配后提供服务的路由地址
#          uri: lb://CLOUD-APPLYMENT-SERVICE #匹配后提供服务的路由地址
#          predicates:
#            - Path=/zn/payment/query/**      #断言，路径相匹配的进行路由

        - id: payment_routh2             #payment_route #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8081    #匹配后提供服务的路由地址
          uri: lb://CLOUD-APPLYMENT-SERVICE #匹配后提供服务的路由地址
          predicates:
            - Path=/zn/payment/query/timeOut        #断言，路径相匹配的进行路由
#            - After=2023-02-21T15:51:37.485+08:00[Asia/Shanghai]   #还有before和between
#            - Before=2000-02-21T15:51:37.485+08:00[Asia/Shanghai]
#            - Cookie=username,zzyy
#            - Header=X-Request-Id,\d+ #请求头要-Request-Id属性并且值为整数的正则表达式






eureka:
  instance:
    hostname: gateway-cloud-service
  client: #服务提供者provider性册住eurake服务列表内
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群版
