server:
  port: 8087

spring:
  application:
    name: cloud-applyment-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/testcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 7464xiong

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群版


#eureka:
#  client:
#    #表示是否将自己注册进EurekaServer默认为true。
#    register-with-eureka: true
#    #是否从Eurekaserver抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡 I
#    fetchRegistry: true
#    service-url:
#      #defaultZone: http://localhost:7001/eureka
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群版
#  instance:
#    #项目在Eurake的别名
#    instance-id: payment-8081
#    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒（默认是30秒）
#    lease-renewal-interval-in-seconds: 2
#    #Eureka服务端在收到最后一次心跳后等待时间上限，单位为秒（默认是90秒），超时将剔除服务
#    lease-expiration-duration-in-seconds: 5


mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-handlers-package: com.zn.springcloud.domain

